import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import type { Database } from "@/integrations/supabase/types";

export type SizeVariantRow = Database["public"]["Tables"]["product_size_variants"]["Row"];

/** What the editor writes. `size_ligne` is generated by the database and never sent. */
export interface SizeVariantWrite {
  id?: string;
  size_primary_mm: number;
  size_secondary_mm: number | null;
  size_label: string | null;
  weight_g: number | null;
  thickness_mm: number | null;
  is_default: boolean;
  sort_order: number;
}

const key = (productId: string) => ["admin-product-sizes", productId] as const;

export function useProductSizeVariants(productId: string) {
  const queryClient = useQueryClient();

  const query = useQuery({
    queryKey: key(productId),
    queryFn: async (): Promise<SizeVariantRow[]> => {
      const { data, error } = await supabase
        .from("product_size_variants")
        .select("*")
        .eq("product_id", productId)
        .order("sort_order", { ascending: true });
      if (error) throw error;
      return data ?? [];
    },
  });

  /**
   * Persists the whole list in one go. Ordered so the partial unique index on
   * is_default can't trip mid-batch: clear every default first, then write
   * rows (with at most one default set by the UI), then delete removed rows.
   */
  const saveAll = useMutation({
    mutationFn: async ({ rows, removedIds }: { rows: SizeVariantWrite[]; removedIds: string[] }) => {
      if (removedIds.length > 0) {
        const { error } = await supabase.from("product_size_variants").delete().in("id", removedIds);
        if (error) throw error;
      }

      const { error: clearError } = await supabase
        .from("product_size_variants")
        .update({ is_default: false })
        .eq("product_id", productId);
      if (clearError) throw clearError;

      const existing = rows.filter((r): r is SizeVariantWrite & { id: string } => !!r.id);
      const fresh = rows.filter((r) => !r.id);

      // Bulk writes need uniform keys per batch — existing rows carry an id, new ones don't.
      if (existing.length > 0) {
        const { error } = await supabase
          .from("product_size_variants")
          .upsert(existing.map((r) => ({ ...r, product_id: productId })), { onConflict: "id" });
        if (error) throw error;
      }
      if (fresh.length > 0) {
        // The `id` KEY must not exist on insert rows, not merely be undefined:
        // postgrest-js lists every key it sees in a `columns=` param, and
        // PostgREST then writes null for any listed column missing from the
        // body — so `{ id: undefined }` becomes `id = null` and the
        // gen_random_uuid() default never applies.
        const { error } = await supabase
          .from("product_size_variants")
          .insert(fresh.map(({ id: _omit, ...r }) => ({ ...r, product_id: productId })));
        if (error) throw error;
      }
    },
    onSuccess: () => queryClient.invalidateQueries({ queryKey: key(productId) }),
  });

  return { query, saveAll };
}
