import { ImgHTMLAttributes, useMemo } from "react";
import manifestData from "@/image-manifest.json";

/**
 * Build-time image manifest (generated by scripts/optimize-images.mjs).
 * Falls back to an empty object if the build script hasn't run yet.
 */
type ManifestEntry = { original: number; variants: { width: number; format: string; path: string; size: number }[] };
const manifest: Record<string, ManifestEntry> = manifestData as Record<string, ManifestEntry>;

// ── Helpers ─────────────────────────────────────────────

type ImagePriority = "eager" | "lazy";

interface OptimizedImageProps extends Omit<ImgHTMLAttributes<HTMLImageElement>, "loading" | "fetchPriority"> {
  /** Original image source (Vite import or public path). */
  src: string;
  alt: string;
  /** Default responsive sizes attribute. */
  sizes?: string;
  /** "eager" for LCP / above-fold, "lazy" for below-fold (default). */
  priority?: ImagePriority;
  /** Extra class names on the <img> element. */
  className?: string;
}

/**
 * Derives the manifest key from a runtime `src` value.
 * Vite-imported assets resolve to e.g. `/assets/hero-image-abc123.jpg` in prod
 * or `/src/assets/hero-image.jpg` in dev. Public assets are just `/foo.jpg`.
 */
function toManifestKey(src: string): string | null {
  if (!src) return null;
  // Already a URL — can't optimise
  if (src.startsWith("http") || src.startsWith("data:")) return null;

  // Try exact public path first (strip leading /)
  const stripped = src.replace(/^\//, "");
  if (manifest[stripped]) return stripped;

  // For Vite-imported assets, try matching by filename stem
  const filename = src.split("/").pop() ?? "";
  // Remove Vite hash: hero-image-abc123.jpg → hero-image
  const stem = filename.replace(/(-[a-zA-Z0-9]{8,})?(\.[^.]+)$/, "");

  for (const key of Object.keys(manifest)) {
    const keyStem = key.replace(/\.[^.]+$/, "").split("/").pop() ?? "";
    if (keyStem === stem) return key;
  }

  return null;
}

function buildSrcSet(
  variants: { width: number; format: string; path: string }[],
  format: string,
): string {
  return variants
    .filter((v) => v.format === format)
    .sort((a, b) => a.width - b.width)
    .map((v) => `${v.path} ${v.width}w`)
    .join(", ");
}

const DEFAULT_SIZES = "(max-width: 480px) 100vw, (max-width: 768px) 80vw, (max-width: 1200px) 60vw, 50vw";

// ── Component ───────────────────────────────────────────

export default function OptimizedImage({
  src,
  alt,
  sizes = DEFAULT_SIZES,
  priority = "lazy",
  className,
  ...rest
}: OptimizedImageProps) {
  const entry = useMemo(() => {
    const key = toManifestKey(src);
    return key ? manifest[key] : null;
  }, [src]);

  const hasAvif = entry?.variants.some((v) => v.format === "avif");
  const hasWebp = entry?.variants.some((v) => v.format === "webp");
  const hasJpg = entry?.variants.some((v) => v.format === "jpg");

  const avifSrcSet = hasAvif ? buildSrcSet(entry!.variants, "avif") : "";
  const webpSrcSet = hasWebp ? buildSrcSet(entry!.variants, "webp") : "";
  const jpgSrcSet = hasJpg ? buildSrcSet(entry!.variants, "jpg") : "";

  const isEager = priority === "eager";

  // No optimised variants — render plain <img>
  if (!entry || entry.variants.length === 0) {
    return (
      <img
        src={src}
        alt={alt}
        loading={isEager ? "eager" : "lazy"}
        decoding={isEager ? "sync" : "async"}
        {...(isEager ? { fetchPriority: "high" } : {})}
        className={className}
        {...rest}
      />
    );
  }

  return (
    <picture>
      {avifSrcSet && <source type="image/avif" srcSet={avifSrcSet} sizes={sizes} />}
      {webpSrcSet && <source type="image/webp" srcSet={webpSrcSet} sizes={sizes} />}
      <img
        src={src}
        srcSet={jpgSrcSet || undefined}
        sizes={jpgSrcSet ? sizes : undefined}
        alt={alt}
        loading={isEager ? "eager" : "lazy"}
        decoding={isEager ? "sync" : "async"}
        {...(isEager ? { fetchPriority: "high" } : {})}
        className={className}
        {...rest}
      />
    </picture>
  );
}
